# Generated by Django 2.2.6 on 2019-12-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('route_number', models.CharField(max_length=30, null=True, verbose_name='Route Number')),
                ('route_zone', models.CharField(max_length=30, null=True, verbose_name='Route Zone')),
                ('route_ns', models.CharField(blank=True, max_length=30, null=True, verbose_name='Route NS')),
                ('route_carrier_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name')),
                ('route_carrier_last_name', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('route_carrier_type', models.CharField(max_length=40, null=True, verbose_name='Carrier Type')),
            ],
        ),
    ]
