# Generated by Django 2.2.6 on 2019-12-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='current_route_ns',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Current Route NS'),
        ),
    ]
