# Generated by Django 2.2.6 on 2019-12-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_current_route_ns'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
