# Generated by Django 2.2.6 on 2020-01-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='holiday',
        ),
    ]
