# Generated by Django 2.2.6 on 2020-01-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_route_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.IntegerField(null=True, verbose_name='Route Number'),
        ),
    ]
