# Generated by Django 2.2.6 on 2020-01-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20200101_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='T6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T6_first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name')),
                ('T6_last_name', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('route_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='T6', to='routes.Route')),
            ],
        ),
    ]
