# Generated by Django 2.2.6 on 2020-01-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_t6'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_pick1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Route 1'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_pick2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Route 2'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_pick3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Route 3'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_pick4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Route 4'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_pick5',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Route 5'),
        ),
        migrations.DeleteModel(
            name='T6',
        ),
    ]
