# Generated by Django 2.2.6 on 2020-01-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20200101_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_pick1',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_pick2',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_pick3',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_pick4',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_pick5',
        ),
    ]
