# Generated by Django 2.2.6 on 2020-01-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20200102_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='T6_carrier_last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='route',
            name='T6_carrier_zone',
            field=models.CharField(max_length=30, null=True, verbose_name='T6 Zone'),
        ),
    ]
