# Generated by Django 2.2.6 on 2020-01-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20200103_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='T6_carrier_zone',
            field=models.CharField(choices=[('20110', '20110'), ('20109', '20109')], default=None, max_length=30, null=True, verbose_name='T6 Zone'),
        ),
        migrations.AlterField(
            model_name='route',
            name='T6_id',
            field=models.CharField(max_length=30, null=True, verbose_name='T6 id'),
        ),
    ]
