# Generated by Django 2.2.6 on 2020-01-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20200104_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='T6_carrier_zone',
            field=models.CharField(choices=[('20109', '20109'), ('20110', '20110')], default=None, max_length=30, null=True, verbose_name='T6 Zone'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_zone',
            field=models.CharField(choices=[('20109', '20109'), ('20110', '20110')], default=None, max_length=30, null=True, verbose_name='Route Zone'),
        ),
    ]
