# Generated by Django 2.2.6 on 2020-01-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='override',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date(YYYY-MM-DD)'),
        ),
    ]
