# Generated by Django 2.2.6 on 2020-01-07 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_auto_20200106_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='T6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T6_carrier_zone', models.CharField(choices=[('20109', '20109'), ('20110', '20110')], default=None, max_length=30, null=True, verbose_name='T6 Zone')),
                ('T6_carrier_last_name', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('route1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route1', to='routes.Route')),
                ('route2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route2', to='routes.Route')),
                ('route3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route3', to='routes.Route')),
                ('route4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route4', to='routes.Route')),
                ('route5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route5', to='routes.Route')),
            ],
        ),
    ]
