# Generated by Django 2.2.6 on 2020-01-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_t6'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T6',
            new_name='T6_employee',
        ),
    ]
