# Generated by Django 2.2.6 on 2020-01-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_auto_20200107_0251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T6_employee',
        ),
    ]
