# Generated by Django 2.2.6 on 2020-01-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0020_route_t6_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='current_route_ns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Route NS'),
        ),
    ]
