# Generated by Django 2.2.6 on 2020-01-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0021_auto_20200107_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='current_route_ns',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Current Route NS'),
        ),
    ]
