# Generated by Django 2.2.6 on 2020-01-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0022_auto_20200107_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='T6_type',
            field=models.CharField(default='T-6', max_length=30, null=True, verbose_name='T6 Type'),
        ),
    ]
