# Generated by Django 2.2.6 on 2020-01-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0024_override_t6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='T6_id',
            field=models.IntegerField(null=True, verbose_name='T6 id'),
        ),
    ]
